# Generated by Django 3.2.8 on 2021-10-21 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='costomer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='titel',
            new_name='title',
        ),
    ]
